name: moshtra
description: E-commerce mobile application for online shopping to purchase a variety of different products in one place, saving effort and time for any user
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

    #SvgPicture
  flutter_svg: ^2.0.8

    #pinput
  pinput: ^3.0.0

    #Smooth_Page_indicator
  smooth_page_indicator: ^1.1.0

    #animatedText
  animated_text_kit: ^4.2.2

    #SharedPref
  shared_preferences: ^2.2.2

    #Get
  get: ^4.6.6

    #AnimateDo
  animate_do: ^3.1.2

    #Responsive
  flutter_screenutil: ^5.9.0

    #AppIcon
  flutter_launcher_icons: ^0.13.1

    #HexColor
  hexcolor: ^3.0.1

    #Check Internet Connection
  connectivity_plus: ^5.0.0
  restart_app: ^1.2.1

    #lottie
  lottie: ^2.7.0

    #easy_loading
  flutter_easyloading: ^3.0.5



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.svg"



  flutter_lints: ^2.0.0


flutter:
    uses-material-design: true

    #Assets
    assets:
      - assets/images/

    #Fonts
    fonts:
      - family: IBMPlex
        fonts:
          - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
            weight: 100
          - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
            weight: 300
          - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
            weight: 400
          - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
            weight: 500
          - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
            weight: 700


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
