name: moshtra
description: E-commerce mobile application for online shopping to purchase a variety of different products in one place, saving effort and time for any user
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  modal_progress_hud_nsn: ^0.5.1
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  flutter:
    sdk: flutter
  status_change: ^2.0.0

    #SvgPicture
  flutter_svg: ^2.0.8

  #FlutterSwitch
  flutter_switch: ^0.3.2

  #FlutterCreditCard
  flutter_credit_card: ^4.0.1

  #Dio
  dio: ^5.4.1

  #carousel_slider
  carousel_slider: ^4.2.1

    #pinput
  pinput: ^3.0.0

  #Shimmer
  shimmer: ^3.0.0

  #web_view
  webview_flutter: ^4.7.0

  #url_lancher
  url_launcher: ^6.0.12

  #conditional_builder
  conditional_builder_null_safety: ^0.0.6

    #Smooth_Page_indicator
  smooth_page_indicator: ^1.1.0

    #animatedText
  animated_text_kit: ^4.2.2

    #refresh
  pull_to_refresh: ^2.0.0

    #SharedPref
  shared_preferences: ^2.2.2

    #Get
  get: ^4.6.1

    #AnimateDo
  animate_do: ^3.1.2

    #Responsive
  flutter_screenutil: ^5.9.0

    #AppIcon
  flutter_launcher_icons: ^0.13.1

    #HexColor
  hexcolor: ^3.0.1

    #Check Internet Connection
  connectivity_plus: ^5.0.0
  restart_app: ^1.2.1

    #lottie
  lottie: ^2.7.0

  #responsive
  responsive_builder: ^0.7.0

    #easy_loading
  flutter_easyloading: ^3.0.5

    #loading_indicator
  loading_indicator: ^3.1.1

  cupertino_icons: ^1.0.2

  #firebase
  firebase_auth: ^4.15.0
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.13.5
  firebase_messaging: ^14.7.21


  #notifications
  flutter_local_notifications: ^17.0.0



  #flutter_stripe
  flutter_stripe: ^10.1.1


  #sqflite
  sqflite: ^2.3.0
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.svg"



  flutter_lints: ^2.0.0


flutter:
    uses-material-design: true

    #Assets
    assets:
      - assets/images/

    #Fonts
    fonts:
      - family: IBMPlex
        fonts:
          - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
            weight: 100
          - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
            weight: 300
          - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
            weight: 400
          - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
            weight: 500
          - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
            weight: 700


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
