// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyPwOixm0Nh5IUWCJGPr8Z0gUbpsg46k4',
    appId: '1:534400976621:web:827fc4559b5ca2fc25eee4',
    messagingSenderId: '534400976621',
    projectId: 'moshtraa',
    authDomain: 'moshtraa.firebaseapp.com',
    storageBucket: 'moshtraa.appspot.com',
    measurementId: 'G-DKLJW04SYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnaYtFLs4n8O0jbi8m2UxHcZvCrb5WfCs',
    appId: '1:534400976621:android:c1577f55900562bb25eee4',
    messagingSenderId: '534400976621',
    projectId: 'moshtraa',
    storageBucket: 'moshtraa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD29lOTxfPJOzSRIfrvdfrrpyksuZQlOBE',
    appId: '1:534400976621:ios:d74f5ff4b6adb1ff25eee4',
    messagingSenderId: '534400976621',
    projectId: 'moshtraa',
    storageBucket: 'moshtraa.appspot.com',
    iosBundleId: 'com.example.moshtra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD29lOTxfPJOzSRIfrvdfrrpyksuZQlOBE',
    appId: '1:534400976621:ios:ad4635e91c409c5025eee4',
    messagingSenderId: '534400976621',
    projectId: 'moshtraa',
    storageBucket: 'moshtraa.appspot.com',
    iosBundleId: 'com.example.moshtra.RunnerTests',
  );
}
